### PR TITLE
Replace the default.py with the one from @mrsprigster

### PR DESCRIPTION
**Pull request by kokarn**
If this is the route you wanna take with it, here's your pull request for it.

### CODE REVIEW

**Comment by Dthibault** [comment]
Nice idea but it's just a temporary fix. For example, we can't choose the quality of the stream.
But it's a very nice idea ;)

**Comment by kokarn** [comment]
Yes I know, but it's something which always is better than nothing. Also it's pretty good because now people can fork my repo instead of replacing the default.py file :)

**Comment by MrSprigster** [comment]
Thanks for this kokarn. I've never submitted to a repository before (I guess it's time to learn). 

Dave

**Comment by Kr0nZ** [comment]
Just thought I would add this
In case you eventually need the nauth and nauthsig (for example in a future twitch api update),
it can be obtained from, (replacing **{{CHANNEL}}** with the channels name):
http://api.twitch.tv/api/channels/{{CHANNEL}}/access_token

nauth = token, nauthsig = sig

found this in a fix for another program that uses twitch 
https://github.com/pencil/Fix-Twitch.tv-Plex-Plugin/blob/master/Fix%20Twitch.tv.bundle/Contents/URL%20Services/Twitch.tv/ServiceCode.pys

**Comment by MrSprigster** [comment]
I've created a much improved fix with Quality options working and Auth added in as a future proofing solution. There's now a pull for this. <a href="https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/pull/49">#49</a>

**Pull request closed without merging**
