### PR TITLE
Sort by last broadcast to get online streams only

### PR DESCRIPTION
**Pull request by kokarn**
This will work up to 100 online channels which should be enough for most of us.

### CODE REVIEW

**Comment by ingwinlu** [comment]
i am a bit lost here

the offline streams that the function returns are used to navigate to highlights and past broadcasts.
Filtering the full list is trivial and does not take long

what is the advantage of your proposed change?

**Comment by kokarn** [comment]
The problem is for people who have more than 100 streams in their follow list, such as me. 
Then only the first 100 are requested and checked if they are online.

Also, as far as I can see the following streams is only used once, [here](https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/blob/7a2dd3f1b42d3625084e5e3f9e060b22184f3862/default.py#L109), and only to build the list of online streams. 
Do you have any reference to where we use it for highlights and past broadcasts? Might be my search-fu that is weak.

**Comment by ingwinlu** [comment]
https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/blob/7a2dd3f1b42d3625084e5e3f9e060b22184f3862/default.py#L115

so your problem does have nothing to do with your purposed change, your problem is you can not view all followed channels, the solution is to query all of them, not change their ordering.

so query all followed streams (the sorting 'could' be used to improve performance, but its way more work then just sorting them), and pass them instead of the artificial 100 limit and bring it more inline with other queries which support pagination.

would you be willing to work on this?

**Comment by kokarn** [comment]
I don't know python that much but I assume your link does what you said it does ^^

It's also true that it has nothing to do with the actual sorting but with how we query things.

I just figured that since this has been a real issue for a long time (#25) this might be a quick and clean way to improve reliability drastically without any risk of breaking anything.

If I read on a bit more (#28) it seems you decided to not to add pagination at all, which seems like a really bad idea considering how this effects the list of channels under "following", ie not listing channels that actually are online.

Since I don't know python I'd rather not get involved in the development :/ (Yes, I know this is a pull request ^^)

How do you feel we should move on? Re-open #28 and add pagination or just merge this for now and deal with the rest later? I'm happy as long as we move forward, following is actually broken as it is now :(

EDIT: Also, @MrSprigster should probably join in here.

**Pull request closed without merging**
