### PR TITLE
adding parameter to set quality when playing streams/videos/clips sin…

### PR DESCRIPTION
**Pull request by dnn1s**
…ce there is no way to set it using JSONRPC. Now you can use something like "plugin://plugin.video.twitch/?mode=play&channel_id=26610234&name=cohhcarnage&quality=720p" to start the stream in the desired quality. I didn't include a function to change the default quality settings or save them on purpose.

### CODE REVIEW

**Comment by anxdpanic** [comment]
plugin://plugin.video.twitch/?mode=edit_qualities
	 Mode: edit_qualities
	 Required parameters: ['content_type'] (stream|video|clip)
	 Optional parameters: ['video_id', 'target_id', 'name', 'remove', 'clip_id']

plugin://plugin.video.twitch/?mode=edit_qualities&content_type=stream&target_id=26610234&name=cohhcarnage would ask user to choose a default quality

* edit corrected plugin url/added content_type

**Comment by anxdpanic** [comment]
plugin://plugin.video.twitch/?mode=play&channel_id=26610234&name=cohhcarnage&ask=true would ask the user for quality ahead of time

**Comment by dnn1s** [comment]
Yes, it does - but it requires user input directly in Kodi, while opening the setting (and not the dialog to choose the setting).

My specific scenario: I wrote a hybrid app that shows concurrent live streams via official Twitch API. It also offers a client-side setting for the desired quality. With v1.4.x, it was possible to use a) the desired stream and b) the desired quality in one JSONRPC call. This is not possible anymore since the quality parameter is not controllable without using the Kodi interface itself.

**Comment by anxdpanic** [comment]
Thanks for the explanation, I was more hesitant due to explicit quality stuff with twitch changing things/varying naming (720p vs '720p - source')  the way they do.

**Pull request merged**
