### PR TITLE
Icons by Goldenfreddy0703

### PR DESCRIPTION
**Pull request by apo86**
Adding the icons made by @Goldenfreddy0703 here https://github.com/anxdpanic/plugin.video.twitch/issues/604

Note: At least in OSMC skin and Estuary as far as I can see, the "icon" of a menu item isn't used anywhere, only the "thumb". So that's where I added them. I don't know if they should also be added as "icon", perhaps for other skins, or reasons I'm not aware of right now?

Also didn't add the Fanart, because there is one already. Personally like them both, wouldn't mind either way.

### CODE REVIEW

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much for making this a pull request. You are the best and im so happy that twitch has icons now. Thank you so much!!!!

**Comment by Goldenfreddy0703** [comment]
Heyyyyyyy its good to see you @anxdpanic and i just gotta say, thank you so much for merging the PR, If there are any other addons that need icons, I will make them for you. 

Again, big thanks to you and you are the best and big thanks to @apo86 too for making this pull request.

**Comment by anxdpanic** [comment]
Thanks to both of you for this, I've pushed the version bump and it's submitted to the official repository 😄

**Comment by apo86** [comment]
Thanks, good to have you back :)

**Pull request merged**
