### PR TITLE
Fix for past broadcasts

### PR DESCRIPTION
**Pull request by spiffomatic64**
fixed a typo, and added missing Play function for past broadcasts
(highlights play now as well, but from the beginning of the past
broadcast)

### CODE REVIEW

**Comment by MrSprigster** [comment]
Thanks :-)

**Comment by spiffomatic64** [comment]
np, looking into the highlight issue, (to prevent having to dig through the code) do you obtain the start position?, right now it looks like the highlights just play the "archive playlist" for whatever archived video the highlight is from

**Comment by MrSprigster** [comment]
I didn't write that particular part of the code so I'd have to look myself and I'm currently mobile so not so easy. I believe the problem with highlights is that we don't have control over xbmc seeking but I could be wrong

**Comment by spiffomatic64** [comment]
as per the api, the play function allows you to set an item from the playlist, and start pos... All we really need is that information from twitch (which I was hoping we already had, but it doesnt look like we scrape for that yet)

http://mirrors.xbmc.org/docs/python-docs/13.0-gotham/xbmc.html#Player

**Comment by spiffomatic64** [comment]
oh nevermind I found the info I think, I should be able to get this working as well :)

**Comment by spiffomatic64** [comment]
ok, after digging into this a bit more... it looks like there are a few options... 

1)if we extend the xbmc player, we can listen for the onPlayBackStarted and seektime then (ideal)
2) have a hardcoded time.sleep followed by a seektime (tested and this works as desired) but this is shitty 
3) set resumetime and total time in the playlist before playing (this is "supposed to work" but I couldnt get it to work, but this is the first xbmc plugin I've touched so I might be missing something obvious)

**Pull request merged**
