### PR TITLE
Fix some stream urls not being detected

### PR DESCRIPTION
**Pull request by Kr0nZ**
Should fix issue #71 

I didn't test it on the mentioned stream in that issue, but I did try all the featured streams and a couple didn't play, seemed to be the same reason that was reported. After these edits, the streams started playing normally.

I removed the "saving url to playlist" as it didn't really seem necessary, hope that's ok, and was kinda the cause of the initial problem. I now just parse the playlist received from twitch for the playable urls.

### CODE REVIEW

**Comment by Giacom** [comment]
Oh thanks, that was annoying.

**Comment by ingwinlu** [comment]
i advise against merging this one yet.
- I don't really see why this should work in the instances where no playable url is found by the old method.
- you lose additional information about the stream you play, like resolution on `Source` quality which is used by some players.
- the name of the method now is misleading and should probably be changed

probably better would be:
keep old method, check how many playable urls are in it and throw an exception if none are retrieved -> if this is the case log the retrieved m3u8 for further debugging

**Comment by Kr0nZ** [comment]
Well the old method would not find playable urls even tho playable urls existed, as I saw in the couple tests I tried. To be honest I couldn't really see how the old method was parsing the file, it seemed to make an assumption that the following 2 lines after finding a quality was all that was needed, which wasn't always the case, sometimes a line with the quality word will exist but will have no corresponding play url, so you would need to select the next best one. My method actually search's for the playable url after finding a quality, or defaults to the first found url.

**Comment by ingwinlu** [comment]
Can you share such a m3u8 which doesn't work with the old method?

**Comment by MrSprigster** [comment]
Thanks for this @Kr0nZ but by using this method we do lose the meta data and I'm aware of some people who use XBMC to create the playlist and then open it with an external video player so I have implemented a simpler fix where we don't lose these features

Cheers,

Sprig

**Pull request closed without merging**
