### PR TITLE
Rework all the things

### LINKED ISSUE #106: VODs no longer working on some videos
Hey, seem to be having a problem viewing certain VODs on new streams like this one: http://www.twitch.tv/hutch/v/3709509

If you try it in XBMC, it gives an error

### PR DESCRIPTION
**Pull request by ingwinlu**
hiho,

this reworks a lot of the plugin:
- moved twitch.py to `twitch/__init__.py` for compability with [python-twitch](https://github.com/ingwinlu/python-twitch)
- playlists are gone and are now parsed directly, returning playable urls
- resolves vod playback issues
- whitespace fixes

also resolves #106 and #108 

music to enjoy while reviewing: https://www.youtube.com/watch?v=JqvAjZEdQR0

### CODE REVIEW

**Comment by ingwinlu** [comment]
updated

**Comment by komadori82** [comment]
Tried these pull requests on my own fork and they work well on my system!

**Comment by MrSprigster** [comment]
Thanks @ingwinlu, things seem to have improved however there are still some errors with VODs (example: cobaltstreak). haven't looked very far into it but I'll increment the addon version and update the changelog when everything is stable again.

Sprig

**Comment by ingwinlu** [comment]
hey @MrSprigster can you share the video id? I tested against the ones which accumulated in issues and it seemed to work fine for me

**Comment by MrSprigster** [comment]
When quickly testing this morning the ID  that was giving me errors was a619273813 (a stream from yesterday evening) which I believe is using the old  API for some reason.

**Comment by Giacom** [comment]
Was the stream under 3 hours long? I think that determines whether it uses the new or old API.

**Comment by MrSprigster** [comment]
Definitely over 3 hours long. Should be easily replicated as at present it's cobaltstreak's most recent VOD. Sorry guys, I haven't had a good chance to get accustomed with the updated code yet due to work commitments and life etc or I'd of looked into it further and provided a better bug report. I'll paste the relevant section of the log when I get home.

Thanks for your time spent on this @ingwinlu

**Comment by MrSprigster** [comment]
Log as promised: http://pastebin.com/Dyp7Fd2R

**Comment by ingwinlu** [comment]
oh for ****\* sake, there are now 3 different types of video playbacks on twitch. ill look into it, thanks for providing the id

**Pull request merged**
